import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import { ThemeProvider } from "@/components/ui/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // icons: [
  //   {
  //     rel: "apple-touch-icon",
  //     url: "/apple-touch-icon.png",
  //   },
  //   {
  //     rel: "icon",
  //     type: "image/png",
  //     sizes: "32x32",
  //     url: "/favicon-32x32.png",
  //   },
  //   {
  //     rel: "icon",
  //     type: "image/png",
  //     sizes: "16x16",
  //     url: "/favicon-16x16.png",
  //   },
  //   {
  //     rel: "icon",
  //     url: "/favicon.ico",
  //   },
  // ],
};

const RootLayout = (
  props: Readonly<{
    children: React.ReactNode;
  }>
) => {
  return (
    <html suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThemeProvider>{props.children}</ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
